apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-auth
  template:
    metadata:
      labels:
        app: postgres-auth
    spec:
      containers:
        - name: postgres
          image: postgres:17-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: test-postgres
            - name: POSTGRES_PASSWORD
              value: test-postgres
            - name: POSTGRES_DB
              value: auth


---
apiVersion: v1
kind: Service
metadata:
  name: postgres-auth-srv
spec:
  selector:
    app: postgres-auth
  ports:
    - port: 5432
      targetPort: 5432