apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bff
  template:
    metadata:
      labels:
        app: bff
    spec:
      initContainers:
        - name: wait-for-rabbitmq
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              echo "Waiting for RabbitMQ..."
              until nc -z rabbitmq 5672; do
                echo "RabbitMQ not ready, sleeping 2s..."
                sleep 2
              done
              echo "RabbitMQ is up!"
      containers:
      - name: bff
        image: tryggsone-bff
        ports:
        - containerPort: 3000
        envFrom:
          - configMapRef:
              name: bff-config
          - configMapRef:
              name: rabbitmq-config
        env: 
          - name: RABBITMQ_USERNAME
            valueFrom:
              secretKeyRef:
                name: rabbitmq-default-user
                key: username
          - name: RABBITMQ_PASSWORD
            valueFrom:
              secretKeyRef:
                name: rabbitmq-default-user
                key: password
---
apiVersion: v1
kind: Service
metadata:
  name: bff-srv
spec:
  selector:
    app: bff
  ports:
  - port: 3000
    targetPort: 3000
