apiVersion: apps/v1
kind: Deployment
metadata:
  name: bikes-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bikes
  template:
    metadata:
      labels:
        app: bikes
    spec:
      containers:
      - name: bikes
        image: tryggsone-bikes
        ports:
        - containerPort: 3000
        env:
          - name: DATABASE_URL
            value: 'postgresql://bikes-postgres:bikes-postgres@postgres-bikes-srv:5432/bikes'

---
apiVersion: v1
kind: Service
metadata:
  name: bikes-srv
spec:
  selector:
    app: bikes
  ports:
  - port: 3000
    targetPort: 3000

